INSERT INTO ADDRESS (STREET, CITY) VALUES ('Bahnhofstrasse 6', 'Windisch');
INSERT INTO ADDRESS (STREET, CITY) VALUES ('Steinackerstrasse 5', 'Windisch');

INSERT INTO CUSTOMER (AGE, NAME, ADDRESS_ID) VALUES(22, 'Mueller', 1);
INSERT INTO CUSTOMER (AGE, NAME, ADDRESS_ID) VALUES(23, 'Schneider', 2);

