INSERT INTO CUSTOMER (ID, EMAIL, FIRSTNAME, LASTNAME) VALUES (1, 'dave@dmband.com', 'Dave', 'Matthews');
INSERT INTO CUSTOMER (ID, EMAIL, FIRSTNAME, LASTNAME) VALUES (2, 'carter@dmband.com', 'Carter', 'Beauford');
INSERT INTO CUSTOMER (ID, EMAIL, FIRSTNAME, LASTNAME) VALUES (3, 'boyd@dmband.com', 'Boyd', 'Tinsley');

INSERT INTO ADDRESS (ID, STREET, CITY, COUNTRY, CUSTOMER_ID) VALUES (1, '17 Broadway', 'New York', 'United States', 1);
INSERT INTO ADDRESS (ID, STREET, CITY, COUNTRY, CUSTOMER_ID) VALUES (2, '27 Broadway', 'New York', 'United States', 1);

INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE) VALUES (1, 'iPad', 'Apple tablet device', 499.0);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE) VALUES (2, 'MacBook Pro', 'Apple notebook', 1299.0);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION, PRICE) VALUES (3, 'Dock', 'Dock for iPhone/iPad', 49.0);

INSERT INTO PRODUCT_ATTRIBUTES (ATTRIBUTES_KEY, PRODUCT_ID, ATTRIBUTES) VALUES ('connector', 1, 'socket');
INSERT INTO PRODUCT_ATTRIBUTES (ATTRIBUTES_KEY, PRODUCT_ID, ATTRIBUTES) VALUES ('connector', 3, 'plug');

INSERT INTO ORDERS (ID, CUSTOMER_ID, SHIPPING_ADDRESS_ID) VALUES (1, 1, 2);
INSERT INTO LINEITEM (ID, PRODUCT_ID, AMOUNT, ORDER_ID, PRICE) VALUES (1, 1, 2, 1, 499.0);
INSERT INTO LINEITEM (ID, PRODUCT_ID, AMOUNT, ORDER_ID, PRICE) VALUES (2, 2, 1, 1, 1299.0);
