INSERT INTO ADDRESS (STREET, CITY) VALUES ('Bahnhofstrasse 6', 'Windisch');

INSERT INTO ORDERS  (ITEM, NUMBER) VALUES ('JPA Book', 35);

INSERT INTO CUSTOMER (AGE, NAME, ADDRESS_ID) VALUES(22, 'Mueller', 1);
INSERT INTO CUSTOMER (AGE, NAME) VALUES(23, 'Schneider');

