CREATE SEQUENCE PUBLIC.MOVIE_SEQUENCE
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;

CREATE MEMORY TABLE PUBLIC.MOVIE(
    ID BIGINT NOT NULL
       DEFAULT NEXT VALUE FOR PUBLIC.MOVIE_SEQUENCE
       NULL_TO_DEFAULT SEQUENCE PUBLIC.MOVIE_SEQUENCE,
    RELEASE_DATE DATE,
    RENTED BOOLEAN NOT NULL,
    TITLE VARCHAR(255),
    ADDITIONAL VARCHAR(255),
    PRIMARY KEY (ID)
)
